### ISSUE TITLE
Features of the points

### ISSUE THREAD

**Issue by kapsl** [dgriffiths3/pointnet2-tensorflow2#10]
Hi,
some time ago there was already a issue about adding features to points. Which would mean having shape (npoints, 4) e.g. Currently this leads to an error, but is supported by the original pointnet++ code. Is it possible to add a feature in this implementation?

Thanks!

**Comment by dgriffiths3** [comment]
Hi, yes this should be possible to add extra features that you don't want to be grouped by the ball query (i.e. anything that isn't coordinates). Using the [cls_ssg](https://github.com/dgriffiths3/pointnet2-tensorflow2/blob/master/models/cls_ssg_model.py) as an example, on [line 72](https://github.com/dgriffiths3/pointnet2-tensorflow2/blob/f2b474a17b38f2f39772698add14ec26084c4934/models/cls_ssg_model.py#L72) I pass `xyz` as `input` and leave `points` as `None`. Instead, you could also pass in your extra channel (be it 1 or `n`) as the `points` here. It would just need to be size: `[batch x num_points x k]` where `k` can be anything.

All that *should* happen is in the `sample_and_group` module at [line 28](https://github.com/dgriffiths3/pointnet2-tensorflow2/blob/f2b474a17b38f2f39772698add14ec26084c4934/pnet2_layers/utils.py#L28) the `points` would *not* be `None` and they would be concatenated at the channel dimensions.

This is exactly what happens in the deeper layers when you have say a point feature with 512 dimensions.

If you wanted the extra channel to be spatially sampled, you would need to rewrite all the cpp modules (i.e. base them on a 4D Euclidean distance). Probably it wouldn't be too hard, mostly just changing 3 to 4 and adding extra for loops.

**Comment by kapsl** [comment]
That worked. Thanks!
