### ISSUE TITLE
Issue Importing tf_sampling_so.so

### ISSUE THREAD

**Issue by as2384** [dgriffiths3/pointnet2-tensorflow2#4]
Hello,
I have followed the steps in the README and compiled the .so shared object libraries for tf_ops. However, my issue is that when I run `python train_modelnet.py' I get the following error:

----------ERROR START-------------
(base) abhii@Ava:~/sandbox/area/python/pointnet2-tensorflow2$ python train_modelnet.py 
Traceback (most recent call last):
  File "train_modelnet.py", line 12, in <module>
    from models.cls_msg_model import CLS_MSG_Model
  File "./models/cls_msg_model.py", line 10, in <module>
    from pnet2_layers.layers import Pointnet_SA, Pointnet_SA_MSG
  File "./pnet2_layers/layers.py", line 4, in <module>
    from . import utils
  File "./pnet2_layers/utils.py", line 8, in <module>
    from .cpp_modules import (
  File "./pnet2_layers/cpp_modules.py", line 9, in <module>
    sampling_module=tf.load_op_library('./tf_ops/sampling/tf_sampling_so.so')
  File "/home/abhii/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./tf_ops/sampling/tf_sampling_so.so: undefined symbol: __cudaPushCallConfiguration
----------ERROR END-------------

Seems like "__cudaPushCallConfiguration" is giving me some issues, any ideas on how to work through this? Thanks for the help.

Environment

Ubuntu 18.04
Python3 3.7.1
CUDA 10.0
Tensorflow 2.0.0
Steps to recreate

Run compile_ops.sh
Download tfrecords for modelnet
Run train_modelnet.py

**Comment by tryptofanik** [comment]
Did you solve this problem? I have xactly the same with cuda 9.0, g++ 5.0 and TF 1.12

**Comment by as2384** [comment]
@tryptofanik I think if you are using TF 1.12 then you are better off using the original github code from Charles Qi. I believe the author David was rewriting PointNet2 for TF2. However, to answer your question, I was able to get it working on another Desktop but my settings were the same... so I have not yet solved it. But I will work on it more this weekend and let you know what I find.

**Comment by tryptofanik** [comment]
Excellent, cant wait to hear from you.

**Comment by dgriffiths3** [comment]
This repository will not work with `tensorflow < 2.2.0`. As pointed out by @as2384 it would be best to use the original implementation for older versions.
