### ISSUE TITLE
loading tf_ops results Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by boboofan** [dgriffiths3/pointnet2-tensorflow2#5]
environment:
Centos 7
Python 3.6.8
TensorFlow-GPU 2.2.0
Cuda 10.1
Cudnn 7.6.5
GCC 4.8.5

While using `tf.load_op_library()` to load tf_ops files in cpp_modules.py, it reports a error `Segmentation fault (core dumped).` And I've tried to use tf-1.+ to load the ops, it also reports the same error. The ops have been compiled under the above environments.

**Comment by dgriffiths3** [comment]
What script are you running when this happens? Can you send the full stack trace?

**Comment by boboofan** [comment]
I call the functions `sample_and_group` and `sample_and_group_all` from the `pnet2_layers.utils` in my self layer. When starting training, the system reports the error `Segmentation fault (core dumped)` if my layer calls `sample_and_group`. And it is ok if my layer calls `sample_and_group_all`.

`python train.py`
`Epoch 1/200`
`Segmentation fault (core dumped)`

**Comment by dgriffiths3** [comment]
What line does it break on? If it `Segmentation fault` then the likely means the error is in the cpp function. This would most likely be that the shape or data type of the variables you are passing in are wrong. This repository uses the original cpp scripts so there error wouldn't be in the script (at least its very unlikely).

**Comment by boboofan** [comment]
I've checked the inputs shape and dtype, it seems they have no problem.
And I ran the raw script `train_modelnet.py`, and it also reported the error.

I debug it and find the error is from:
`layers.py`:
`Pointnet_SA_MSG.call()`: 
`new_xyz = utils.gather_point(xyz, utils.farthest_point_sample(self.npoint, xyz))`

`cpp_modules.py`:
`farthest_point_sample()`: 
`return sampling_module.farthest_point_sample(inp, npoint)`
