### ISSUE TITLE
 Is there any way I can use it with our dataset?

### ISSUE THREAD

**Issue by stevebong31** [dgriffiths3/pointnet2-tensorflow2#7]
Hello.
We now have n x 3 data in NumPy.
But when I looked for your project, it used tfrecord. So I'm looking for code to convert our data to tfrecord and it's not easy. Any advice on how to approach it? Thank you.

**Comment by dgriffiths3** [comment]
Hello,

Yes, creating a tfrecord from a numpy n x 3 array is a relatively simple process. Check out the tensorflow docs on how to generate a tfrecord here: https://www.tensorflow.org/tutorials/load_data/tfrecord

If you would like to see an example of create one with a point cloud check out the code in my other repository: https://github.com/dgriffiths3/mononet3d/blob/master/datasets/create_tfrecord.py The `scan` is an n x 3 array so you can just ignore all the other bits.

**Comment by stevebong31** [comment]
Thanks alot!
