### ISSUE TITLE
 how to change cpp_wrappers(https://github.com/HuguesTHOMAS/KPConv/tree/master/cpp_wrappers) in the KPConv that can be compiled by tensorflow2？

### ISSUE THREAD

**Issue by longmalongma** [dgriffiths3/pointnet2-tensorflow2#9]
Thank you for your great work Pointnet2-tensorflow2, I think this is a very meaningful work. I have a question to ask you, how to change cpp_wrappers(https://github.com/HuguesTHOMAS/KPConv/tree/master/cpp_wrappers) in the KPConv that can be compiled by tensorflow2？How can I change this compiler to make tensorflow2 compile it? I tried it many times and couldn't complete it. Can you help me modify cpp_wrappers so that it can compile it with tensorflow2?
Now this package can only be compiled only under tensorflow1, because my environment is based on tensorflow2, cuda11.0, if you can help me modify it so that it can be compiled under tensorflow2, I will thank you very much. Looking forward to your reply.

**Comment by dgriffiths3** [comment]
Hi, the link you send is to cpp code that has nothing to do with tensorflow from what I can tell. The custom tensorflow ops are located here: https://github.com/HuguesTHOMAS/KPConv/tree/master/tf_custom_ops. The custom tensorflow ops should still compile fine with cuda11.0 although i have never done this myself. If you get errors i imagine other people in the tensorflow community are getting the same ones.

You say the wrappers you are compiling don't compile 'under' tensorflow 2. What exactly do you mean by this?
